version: '3'

services:
  db:
    container_name: notas-poli-bd
    image: mongo:latest
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - mi_red_compartida

networks:
  mi_red_compartida:
    external: true
